version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: warter_pie_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: warter_pie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: